name: Sisl PR Build

on:
  pull_request:
    branches:
      - master

jobs:
  build_deps:
    strategy:
      fail-fast: true
      matrix:
        build-type: ["Debug", "Release"]
        malloc-impl: ["libc", "tcmalloc", "jemalloc"]
        exclude:
          - build-type: Debug
            malloc-impl: tcmalloc
          - build-type: Debug
            malloc-impl: jemalloc
          - build-type: Release
            malloc-impl: libc
    uses: ./.github/workflows/build_dependencies.yml
    with:
      branch: master
      build-type: ${{ matrix.build-type }}
      malloc-impl: ${{ matrix.malloc-impl }}
      prerelease: "True"
      native: 'true'
